//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string email { get; set; }
        public string pan_number { get; set; }
        public string gst_number { get; set; }
        public string mobile { get; set; }
        public Nullable<int> tenant_id { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
