//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialYear
    {
        public FinancialYear()
        {
            this.Companies = new HashSet<Company>();
            this.InvoiceMasters = new HashSet<InvoiceMaster>();
            this.PrinterChalans = new HashSet<PrinterChalan>();
            this.PrintJobWorkReceiveds = new HashSet<PrintJobWorkReceived>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.TailorChalans = new HashSet<TailorChalan>();
            this.TailorChalanSends = new HashSet<TailorChalanSend>();
            this.Tenants = new HashSet<Tenant>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual ICollection<PrinterChalan> PrinterChalans { get; set; }
        public virtual ICollection<PrintJobWorkReceived> PrintJobWorkReceiveds { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<TailorChalan> TailorChalans { get; set; }
        public virtual ICollection<TailorChalanSend> TailorChalanSends { get; set; }
        public virtual ICollection<Tenant> Tenants { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
