//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialYear
    {
        public FinancialYear()
        {
            this.InvoiceMasters = new HashSet<InvoiceMaster>();
            this.Tenants = new HashSet<Tenant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual ICollection<Tenant> Tenants { get; set; }
    }
}
