//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterChalan
    {
        public PrinterChalan()
        {
            this.PrinterChalanDetails = new HashSet<PrinterChalanDetail>();
        }
    
        public int Id { get; set; }
        public int VendorId { get; set; }
        public System.DateTime ChalanDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Description { get; set; }
        public bool IsGivenToPrinting { get; set; }
    
        public virtual ICollection<PrinterChalanDetail> PrinterChalanDetails { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
