//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TailorChalanSendDetail
    {
        public int Id { get; set; }
        public int ChalanId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TailorChalanSend TailorChalanSend { get; set; }
        public virtual TailorChalanSend TailorChalanSend1 { get; set; }
    }
}
