//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.Customers = new HashSet<Customer>();
            this.InvoiceMasters = new HashSet<InvoiceMaster>();
            this.PrinterChalans = new HashSet<PrinterChalan>();
            this.PrintJobWorkReceiveds = new HashSet<PrintJobWorkReceived>();
            this.Products = new HashSet<Product>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.TailorChalans = new HashSet<TailorChalan>();
            this.TailorChalanSends = new HashSet<TailorChalanSend>();
            this.Transactions = new HashSet<Transaction>();
            this.Users = new HashSet<User>();
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> CurrentFinYear { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual FinancialYear FinancialYear { get; set; }
        public virtual ICollection<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual ICollection<PrinterChalan> PrinterChalans { get; set; }
        public virtual ICollection<PrintJobWorkReceived> PrintJobWorkReceiveds { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<TailorChalan> TailorChalans { get; set; }
        public virtual ICollection<TailorChalanSend> TailorChalanSends { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
